Describe "PSCustomObject Creation Performance" {
    $ObjectsToConvert = [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/08/2003 09:13:36
        database_id = 1
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_db_chaining_on = True
        log_reuse_wait = 7
        log_reuse_wait_desc = "DATABASE_SNAPSHOT_CREATION"
        name = "master"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 00000000-0000-0000-0000-000000000000
        snapshot_isolation_state = 1
        snapshot_isolation_state_desc = "ON"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 05/23/2018 14:58:41
        database_id = 2
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_db_chaining_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "tempdb"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = caebce2f-e9a8-4dca-bcb0-27ebad8ae888
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/08/2003 09:13:36
        database_id = 3
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "model"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 00000000-0000-0000-0000-000000000000
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/02/2010 17:35:08
        database_id = 4
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_db_chaining_on = True
        is_fulltext_enabled = True
        is_trustworthy_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "msdb"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 87178734-e5f1-4c17-8bd8-ce55ca87e72e
        snapshot_isolation_state = 1
        snapshot_isolation_state_desc = "ON"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 01/26/2013 07:58:34
        database_id = 5
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait = 7
        log_reuse_wait_desc = "DATABASE_SNAPSHOT_CREATION"
        name = "ReportServer"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = a61549b5-434b-4535-9c1b-5ba3efb720c4
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 01/26/2013 07:59:17
        database_id = 6
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "ReportServerTempDB"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 6fdf49a7-2eea-4a3c-b8ec-25693ccc4d56
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/24/2012 21:15:19
        database_id = 7
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asfdasdfas"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 2fee8f7e-2944-4c78-a21f-eacb42ac344c
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 07/10/2014 14:47:39
        database_id = 8
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfsafd"
        owner_sid = 1100000518000
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 74510d21-47b8-43d9-a9fa-ffba7a734db3
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state = 6
        state_desc = "OFFLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/03/2013 22:22:37
        database_id = 10
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfsadf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 57cb70dc-b43f-4b68-9b5e-c9fd8916ea7f
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/02/2014 10:22:22
        database_id = 11
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasfd"
        owner_sid = 123412341234
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 5d20ced9-e5d4-4167-9a0c-4b8ba62d4151
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/02/2014 10:21:56
        database_id = 12
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfsadf"
        owner_sid = 1234123412342
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = eb4a3b16-386f-42f0-b731-e34b67698941
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/30/2011 10:19:44
        database_id = 13
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_cursor_close_on_commit_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_read_committed_snapshot_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasfd"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 8eba9681-bdac-4a19-a48e-d32b42613eaa
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/30/2011 09:26:30
        database_id = 14
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasfdasfdasf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = fb1f0b9e-c587-4fef-888b-292340f9ae77
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/24/2012 22:21:46
        database_id = 16
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasfd"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 4a2e485c-7373-4146-9f4e-99067b18f4f9
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/04/2014 08:06:21
        database_id = 17
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        is_read_committed_snapshot_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asfasdfasdfasf"
        owner_sid = 1121234123412
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 05582a60-a480-4b4a-a63b-1b5b4816e1c4
        snapshot_isolation_state = 1
        snapshot_isolation_state_desc = "ON"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/30/2011 10:18:34
        database_id = 18
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_cursor_close_on_commit_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_read_committed_snapshot_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfsadf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 216f378f-db0b-47c3-8c7c-2a156ad7c5cd
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 08/13/2013 14:27:59
        database_id = 21
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 123412342134
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = ef0996ff-02ce-4a43-9d40-d86e31949c57
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 08/13/2013 14:44:15
        database_id = 22
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 123412341234
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 94e1e54d-0312-47d7-84f7-4cd1bcb2b179
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 08/13/2013 14:45:24
        database_id = 23
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfas"
        owner_sid = 1234124
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 3d140e54-d831-46f2-9bed-53f26a543a09
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 03/02/2014 10:28:19
        database_id = 24
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 123412341234
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 45d77a75-189b-4675-900d-7b5bd09caa76
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 15:06:17
        database_id = 25
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 511d5073-2d23-44dd-bfd4-a6357a337953
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/24/2012 22:21:59
        database_id = 26
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        log_reuse_wait = 2
        log_reuse_wait_desc = "LOG_BACKUP"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 07915094-9529-4c98-be0c-294783bf9092
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/02/2014 09:24:07
        database_id = 27
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 12341234124
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = a5ba0ab0-d133-4c7d-b43e-d507d21f07a1
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 15:06:18
        database_id = 28
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 03e9eac5-6c65-4e98-ba85-678c351f326e
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 02/03/2017 07:22:50
        database_id = 29
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "adsfasdfasdfasfd"
        owner_sid = 1
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 2c37e869-0405-46ed-923c-5ca7a788cc0e
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 09/14/2011 11:11:16
        database_id = 31
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 1
        page_verify_option_desc = "TORN_PAGE_DETECTION"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 3887f1b4-da4c-4a6f-8441-234711acc074
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 15:06:19
        database_id = 32
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait = 7
        log_reuse_wait_desc = "DATABASE_SNAPSHOT_CREATION"
        name = "asdfasdasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = c5c3875b-08a4-4a02-b772-88df96ec08e6
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 04/24/2012 22:22:05
        database_id = 35
        is_broker_enabled = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        log_reuse_wait = 2
        log_reuse_wait_desc = "LOG_BACKUP"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 423e4535-9bb3-42a1-9c5a-20704d35fd10
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 17:23:39
        database_id = 36
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 02104452-30a4-433f-b173-c6d2aa206bd2
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 17:28:56
        database_id = 37
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait = 1
        log_reuse_wait_desc = "CHECKPOINT"
        name = "asdfasdasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 5aebee61-17ff-49fc-949e-6e28fee0dc49
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 17:29:40
        database_id = 38
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = bf0c8b4a-f4f8-4b2d-a0d6-1c5df255f706
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 01/13/2017 13:41:06
        database_id = 39
        is_ansi_nulls_on = True
        is_ansi_null_default_on = True
        is_ansi_padding_on = True
        is_ansi_warnings_on = True
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_concat_null_yields_null_on = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        is_quoted_identifier_on = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasfasfasf"
        owner_sid = 123412341234
        page_verify_option_desc = "NONE"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = ed3aec14-c9cd-4fa3-aecf-6229086f8170
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/16/2012 15:38:34
        database_id = 40
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 2cd0b6a0-af7a-46e4-af31-0e1bc7ea17b9
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 90
        create_date = 07/24/2012 19:58:07
        database_id = 41
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait = 2
        log_reuse_wait_desc = "LOG_BACKUP"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = 28764304-6692-4c35-a4ca-bb30479b6f94
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 01/06/2015 16:22:18
        database_id = 42
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait = 2
        log_reuse_wait_desc = "LOG_BACKUP"
        name = "asdfasfasdfasfd"
        owner_sid = 123412341241
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = ae3ac5df-8e1a-47d5-81c9-543a38d28c84
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 06/06/2015 09:10:59
        database_id = 44
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 123412341
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 4034828f-47ce-4c93-8b11-53821c1d19d3
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 10/01/2012 20:56:55
        database_id = 48
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 1
        recovery_model_desc = "FULL"
        service_broker_guid = d05a620b-0e87-41b6-b63a-a1f26e48b98b
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 100
        create_date = 10/01/2012 20:56:57
        database_id = 49
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        is_local_cursor_default = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 0f8f02b6-defd-4ffe-9e6d-016b60661e5a
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "SQL_Latin1_General_CP1_CI_AS"
        compatibility_level = 90
        create_date = 03/03/2016 12:45:34
        database_id = 77
        is_auto_close_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_fulltext_enabled = True
        log_reuse_wait = 7
        log_reuse_wait_desc = "DATABASE_SNAPSHOT_CREATION"
        name = "asdfasfasdf"
        owner_sid = 1
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = e49e6198-f40b-4a90-b76a-4c5d4f2df2a1
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    },
    [PSCustomObject][Ordered]@{
        collation_name = "Latin1_General_CI_AS_KS_WS"
        compatibility_level = 100
        create_date = 07/25/2016 11:48:29
        database_id = 80
        is_arithabort_on = True
        is_auto_create_stats_on = True
        is_auto_update_stats_on = True
        is_broker_enabled = True
        is_fulltext_enabled = True
        log_reuse_wait_desc = "NOTHING"
        name = "asdfasdfasdf"
        owner_sid = 12341234214
        page_verify_option = 2
        page_verify_option_desc = "CHECKSUM"
        recovery_model = 3
        recovery_model_desc = "SIMPLE"
        service_broker_guid = 34e425a5-170c-4eb4-8ad5-d33201887253
        snapshot_isolation_state_desc = "OFF"
        source_database_id =
        state_desc = "ONLINE"
        user_access_desc = "MULTI_USER"
    }

    It "Ordered Dictionary converted to PSCustomObject" {

    }
}